version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php-fpm
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    environment:
        DB_HOST: mysql-db
        DB_PORT: 3306
    networks:
      - webnet
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data: